# -*- coding: utf-8 -*-
"""LangChain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wUFDc9xQFIVRouczZnOqZqMrY8oBNJzm
"""

# Cell 1 — Install dependencies
!uv pip install langchain langchain-community langchain-openai langchain-text-splitters faiss-cpu tiktoken pypdf transformers==4.44.0 accelerate beautifulsoup4 tqdm

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline
from langchain_community.llms import HuggingFacePipeline
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
from langchain_community.document_loaders import PyPDFLoader

# 1. LLM — flan-t5-base runs on CPU, no GPU needed
# Load model and tokenizer directly
tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-base")
model = AutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-base")

# Create a pipeline with the loaded model and tokenizer
pipe = pipeline(
    "text2text-generation",
    model="google/flan-t5-base",
    max_new_tokens=256,
    truncation=True,        # ← silences the indexing warning
    model_kwargs={"max_length": 512}
)

llm = HuggingFacePipeline(pipeline=pipe)

# 2. Embeddings — free, runs locally
embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

# 3. Load, split, store (same as before)
loader = PyPDFLoader("Appellate_Division_Courthouse_of_New_York_State.pdf")
docs = loader.load()
splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,       # Max characters per chunk
    chunk_overlap=50,     # Overlap between chunks to preserve context
    separators=["\n\n", "\n", ". ", " ", ""]
)

chunks = splitter.split_documents(docs)
vectorstore = FAISS.from_documents(chunks, embeddings)
retriever = vectorstore.as_retriever(search_type="similarity",search_kwargs={"k": 4})

# 4. Use PromptTemplate instead of ChatPromptTemplate
#    flan-t5 expects a plain string prompt, not chat messages
prompt = PromptTemplate.from_template("""
Answer the question using only the context below.
If the answer is not in the context, say "I don't know."

Context: {context}

Question: {question}

Answer:
""")

def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)

# 5. Chain — identical structure
chain = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

answer = chain.invoke("How tall is the roof of the Appellate Division Courthouse?")
print(answer)

question = "Who designed the Appellate Division Courthouse?"

print("=" * 50)
print("WITHOUT RAG (flan-t5-base only)")
print("=" * 50)
raw_answer = llm.invoke(question)
print(raw_answer)  # plain string, no .content

print("\n" + "=" * 50)
print("WITH RAG (flan-t5-base + your PDF)")
print("=" * 50)
rag_answer = chain.invoke(question)
print(rag_answer)

from google.colab import drive
drive.mount('/content/drive')

import os

drive_path = '/content/drive/MyDrive'

# # List contents of the root of MyDrive
# print(f"Contents of {drive_path}:")
# for item in os.listdir(drive_path):
#     print(item)

from pathlib import Path

txt_files = list(Path('/content/drive/MyDrive/sec-edgar-filings').glob('**/*.txt'))
print(len(txt_files))

from bs4 import BeautifulSoup
from pathlib import Path

input_dir = Path('/content/drive/MyDrive/sec-edgar-filings')
output_dir = Path('./sec-edgar-filings')
output_dir.mkdir(exist_ok=True)

for file in input_dir.glob('**/*.txt'):
    with open(file, 'r', errors='ignore') as f:
        soup = BeautifulSoup(f, 'html.parser')
        # Remove noise
        for tag in soup(['script', 'style', 'nav', 'footer']):
            tag.decompose()
        text = soup.get_text(separator='\n', strip=True)

    # Save clean text mirroring folder structure
    out_file = output_dir / file.relative_to(input_dir)
    out_file.parent.mkdir(parents=True, exist_ok=True)
    out_file.write_text(text)

print("Done preprocessing")

"""### Embedding"""

from langchain_community.document_loaders import DirectoryLoader, BSHTMLLoader, TextLoader, PyPDFLoader
import itertools
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from tqdm import tqdm

# Load different files types within docs directory
loaders = [
    DirectoryLoader('./sec-edgar-filings', glob="**/*.txt",  loader_cls=TextLoader, use_multithreading=True),
    DirectoryLoader('/content/drive/MyDrive/sec-edgar-filings', glob="**/*.html", loader_cls=BSHTMLLoader),
    DirectoryLoader('/content/drive/MyDrive/sec-edgar-filings', glob="**/*.pdf",  loader_cls=PyPDFLoader),
]

docs = list(itertools.chain.from_iterable(l.load() for l in loaders))
print('Documents Loaded')

splitter = RecursiveCharacterTextSplitter(chunk_size=512, chunk_overlap=64)
chunks = splitter.split_documents(docs)
print('Finished Chunking')
print(len(chunks))
# Embed with a local sentence-transformer model
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2", encode_kwargs={"batch_size": 1024})
print('Embeddings Created')


vectorstore = FAISS.from_documents(tqdm(chunks, desc="Embedding"), embeddings)
vectorstore.save_local("faiss_index")

"""## New Model No Finetuning yet"""

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline, BitsAndBytesConfig
from langchain_community.llms import HuggingFacePipeline
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough, RunnableParallel
from langchain_core.prompts import ChatPromptTemplate


model_id = "microsoft/Phi-3-mini-4k-instruct"

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    device_map="auto",
    trust_remote_code=True
)
tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token

pipe = pipeline(
    "text-generation", model=model, tokenizer=tokenizer,
    max_new_tokens=256, temperature=0.1, do_sample=True,
    return_full_text=False
)
llm = HuggingFacePipeline(pipeline=pipe)

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2",
    model_kwargs={"device": "cuda"}
)
vectorstore = FAISS.load_local(
    "./faiss_index", embeddings,
    allow_dangerous_deserialization=True
)
retriever = vectorstore.as_retriever(search_kwargs={"k": 4})

def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)

prompt = ChatPromptTemplate.from_template("""Answer the question based only on the following context:

{context}

Question: {question}
""")

# Chain that also returns source documents
retrieval_chain = RunnableParallel(
    context=retriever | format_docs,
    question=RunnablePassthrough(),
    source_documents=retriever
)

chain = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

question = "What was the gross margin for products and services for this quarter?"
result = chain.invoke(question)
print(result)

# If you also need source documents:
# source_docs = retriever.invoke(question)
# for doc in source_docs:
#     print(doc.metadata)

"""## Not Working"""



"""## Fine-Tuning"""

from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments
from peft import LoraConfig, get_peft_model
from trl import SFTTrainer
from datasets import load_dataset

model_id = "microsoft/phi-3-mini-4k-instruct"  # or mistralai/Mistral-7B-Instruct-v0.2

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(model_id, load_in_4bit=True)

lora_config = LoraConfig(
    r=16, lora_alpha=32,
    target_modules=["q_proj", "v_proj"],
    lora_dropout=0.05, bias="none",
    task_type="CAUSAL_LM"
)
model = get_peft_model(model, lora_config)

dataset = load_dataset("json", data_files="train.jsonl", split="train")

def format_example(row):
    return {"text": f"{row['prompt']}\n\nAnswer: {row['completion']}"}

dataset = dataset.map(format_example)

trainer = SFTTrainer(
    model=model,
    train_dataset=dataset,
    dataset_text_field="text",
    args=TrainingArguments(
        output_dir="./fine-tuned-model",
        num_train_epochs=3,
        per_device_train_batch_size=4,
        gradient_accumulation_steps=4,
        learning_rate=2e-4,
        save_steps=100,
    )
)
trainer.train()
model.save_pretrained("./fine-tuned-model")

"""## Run the model fine-tuned"""

from langchain_community.llms  import HuggingFacePipeline
from langchain_community.vectorstores import FAISS
from langchain.embeddings import HuggingFaceEmbeddings
from transformers import pipeline, AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel
from langchain_core.runnables import RunnablePassthrough, RunnableParallel
from langchain_core.prompts import ChatPromptTemplate

# Load fine-tuned model
base = AutoModelForCausalLM.from_pretrained("microsoft/phi-3-mini-4k-instruct", load_in_4bit=True)
model = PeftModel.from_pretrained(base, "./fine-tuned-model")
tokenizer = AutoTokenizer.from_pretrained("microsoft/phi-3-mini-4k-instruct")

pipe = pipeline("text-generation", model=model, tokenizer=tokenizer,
                max_new_tokens=256, temperature=0.1)
llm = HuggingFacePipeline(pipeline=pipe)

# Load vector store
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
vectorstore = FAISS.load_local("faiss_index", embeddings)
retriever = vectorstore.as_retriever(search_kwargs={"k": 4})

# RAG chain
prompt = ChatPromptTemplate.from_template("""Answer the question based only on the following context:

{context}

Question: {question}
""")

# Chain that also returns source documents
retrieval_chain = RunnableParallel(
    context=retriever | format_docs,
    question=RunnablePassthrough(),
    source_documents=retriever
)

chain = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

while True:
    question = input("You: ").strip()

    if not question:
        print("Please enter a question.\n")
        continue

    if question.lower() in ["exit", "quit"]:
        print("Goodbye!")
        break

    print("Thinking...\n")
    answer = "answer"
    print(f"Answer: {answer}\n")
    print("-" * 50)

